#!/usr/bin/env bash
# readme-gen — Scaffold README.md from repo structure
# Usage: readme-gen [DIR] [-o FILE] [-f]
set -uo pipefail
IS_TTY=0; [[ -t 1 ]] && IS_TTY=1
HAS_GUM=0; [[ "$IS_TTY" -eq 1 ]] && command -v gum >/dev/null 2>&1 && HAS_GUM=1
if [[ "$IS_TTY" -eq 1 ]]; then
  G=$'\e[32m' Y=$'\e[33m' B=$'\e[1m' X=$'\e[0m'
else
  G='' Y='' B='' X=''
fi
print_ok()   { printf '%s\n' "${G}  [  OK  ]${X} ${1}"; }
print_warn() { printf '%s\n' "${Y}  [ WARN ]${X} ${Y}${1}${X}"; }
clr()        { [[ "$IS_TTY" -eq 1 ]] && printf '\033[2J\033[H'; }
banner() {
  clr; printf '\n'
  if [[ "$HAS_GUM" -eq 1 ]]; then
    gum style --foreground "#00cc44" --border double --border-foreground "#00cc44" \
      --align center --width 60 --margin "0 2" --padding "1 3" \
      "R E A D M E   G E N" "" "Scaffold README from Repo"
    printf '\n'
  fi
}
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

TARGET=""; OUTPUT=""; FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    -o|--output) OUTPUT="$2"; shift 2 ;;
    -f|--force)  FORCE=1; shift ;;
    -*) shift ;; *) TARGET="$1"; shift ;;
  esac
done
if [[ -z "$TARGET" ]]; then
  prompt_dir TARGET "Repository root" "readme-gen.last_dir" || exit 1
else
  TARGET="$(cd "$TARGET" && pwd)"
  state_set "readme-gen.last_dir" "$TARGET"
fi
[[ -z "$OUTPUT" ]] && OUTPUT="$TARGET/README.md"
[[ -f "$OUTPUT" && "$FORCE" -eq 0 ]] && { print_warn "${OUTPUT} exists. Use -f to overwrite."; exit 1; }
banner
python3 - "${TARGET}" "${OUTPUT}" << 'PY'
import sys, json, re
from pathlib import Path
from datetime import date as dt
target, outfile = Path(sys.argv[1]), Path(sys.argv[2])
name = target.name
has_py = bool(list(target.glob("*.py"))) or (target/"requirements.txt").exists()
has_node = (target/"package.json").exists()
has_go = bool(list(target.glob("*.go")))
lang = "Python" if has_py else ("Node.js" if has_node else ("Go" if has_go else "Bash/Shell"))
desc = ""
scripts_md = ""
if has_node:
    try:
        pkg = json.loads((target/"package.json").read_text())
        desc = pkg.get("description","")
        scripts = pkg.get("scripts",{})
        if scripts:
            lines = "".join(f"npm run {k}   # {v}\n" for k,v in list(scripts.items())[:8])
            scripts_md = "## Scripts\n\n```bash\n" + lines + "```\n\n"
    except: pass
install_cmd = "pip install -r requirements.txt" if has_py else ("npm install" if has_node else "# See SETUP.md")
run_cmd = "python3 main.py" if has_py else ("npm start" if has_node else ("go run ." if has_go else "bash ./script.sh"))
readme = f"""# {name}

> {desc or f"A {lang} project."}

## Overview

Add description here.

## Prerequisites

- {lang}

## Installation

```bash
git clone <repo-url>
cd {name}
{install_cmd}
```

## Usage

```bash
{run_cmd}
```

{scripts_md}## Configuration

Document environment variables and config files here.

## Contributing

1. Fork and create a feature branch
2. Commit with [Conventional Commits](https://www.conventionalcommits.org)
3. Open a pull request

---
*Generated by readme-gen on {dt.today()}*
"""
outfile.write_text(readme)
print(f"Written: {outfile}")
PY
print_ok "README.md → ${B}${OUTPUT}${X}"
